package com.donotmiss.backend.agentlog;

public enum AgentRunType {
    EVENT_RECOMMENDATION,
    PLAN_RECOMMENDATION,
    GROWTH_TAG_EXTRACTION,
    EVENT_QUALITY_ANALYSIS,
    ABILITY_EVIDENCE_ASSESSMENT,
    ABILITY_JUDGE,
    BAD_CASE_INTAKE,
    RESUME_EXTRACTION,
    JOB_REQUIREMENT_EXTRACTION,
    JOB_REQUIREMENT_RETRIEVAL,
    CANDIDATE_JOB_GAP_ANALYSIS
}
