package com.donotmiss.backend.aiapplication.career.gap;

import com.donotmiss.backend.agentlog.*; import com.donotmiss.backend.aiapplication.agent.*; import com.donotmiss.backend.aiapplication.career.*; import com.donotmiss.backend.aiapplication.career.job.*; import com.donotmiss.backend.common.ApiException; import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.Instant; import java.util.*;

/** Candidate–Job vertical slice. It uses only candidate evidence, structured job requirements, AgentRuntime and LlmGateway. */
@Service public class GapAnalysisService {
 private final ResumeVersionRepository resumes; private final CandidateProfileSnapshotRepository profiles; private final CandidateEvidenceRepository evidence; private final JobRequirementVersionRepository jobs; private final StructuredJobRequirementRepository requirements; private final GapAnalysisRepository analyses; private final GapAnalysisItemRepository items; private final GapAnalysisPolicy policy; private final AgentRuntime runtime; private final AgentRunService agentRuns; private final ObjectMapper mapper;
 public GapAnalysisService(ResumeVersionRepository resumes,CandidateProfileSnapshotRepository profiles,CandidateEvidenceRepository evidence,JobRequirementVersionRepository jobs,StructuredJobRequirementRepository requirements,GapAnalysisRepository analyses,GapAnalysisItemRepository items,GapAnalysisPolicy policy,AgentRuntime runtime,AgentRunService agentRuns,ObjectMapper mapper){this.resumes=resumes;this.profiles=profiles;this.evidence=evidence;this.jobs=jobs;this.requirements=requirements;this.analyses=analyses;this.items=items;this.policy=policy;this.runtime=runtime;this.agentRuns=agentRuns;this.mapper=mapper;}
 @Transactional public GapAnalysisDtos.Result analyze(String userId,Long jobVersionId,GapAnalysisDtos.RunRequest request){ResumeVersionEntity resume=resumes.findByIdAndUserId(request.resumeVersionId(),userId).orElseThrow(()->ApiException.notFound("Resume version not found."));JobRequirementVersionEntity job=jobs.findByIdAndUserId(jobVersionId,userId).orElseThrow(()->ApiException.notFound("Job requirement version not found."));CandidateProfileSnapshotEntity profile=profiles.findByResumeVersionIdAndUserId(resume.getId(),userId).orElseThrow(()->ApiException.badRequest("Candidate profile must be parsed before gap analysis."));List<CandidateEvidenceEntity> candidateEvidence=evidence.findByUserIdAndProfileSnapshotIdOrderByCreatedAtAsc(userId,profile.getId());List<StructuredJobRequirementEntity> structured=requirements.findByJobRequirementVersionIdOrderByIdAsc(job.getId());if(structured.isEmpty())throw ApiException.badRequest("Job requirement must be parsed before gap analysis.");
  String resumeHash=hash(String.valueOf(resume.getId())), jobHash=hash(String.valueOf(job.getId()));Long runId=agentRuns.startRun(userId,AgentRunType.CANDIDATE_JOB_GAP_ANALYSIS,"gap-analysis:resume:"+resume.getId()+":job:"+job.getId(),"resumeVersionHash="+resumeHash+", jobVersionHash="+jobHash+", requirementCount="+structured.size());Long deterministicStep=agentRuns.startStep(runId,AgentStepName.GAP_DETERMINISTIC_MATCH,"Match by skill code and explicit level; no raw evidence is traced.");
  try {List<ItemDraft> drafts=new ArrayList<>();int semanticCount=0;for(StructuredJobRequirementEntity requirement:structured){List<CandidateEvidenceEntity> matching=candidateEvidence.stream().filter(e->requirement.getSkillCode().equals(e.getSkillCode())).toList();GapDeterministicMatch match=policy.deterministic(!matching.isEmpty(),evidenceLevel(matching),requirement.getRequiredLevel());GapSemanticAssessment semantic=null;if(match==GapDeterministicMatch.SEMANTIC_REVIEW){semanticCount++;semantic=semantic(runId,userId,requirement,matching,resumeHash,jobHash);}GapAnalysisPolicy.Decision decision=policy.decide(match,semantic);drafts.add(new ItemDraft(requirement,matching,decision));}agentRuns.completeStep(deterministicStep,"requirementCount="+structured.size()+", semanticCount="+semanticCount);Long policyStep=agentRuns.startStep(runId,AgentStepName.GAP_POLICY_APPLY,"Apply deterministic gap policy.");GapAnalysisDtos.Summary summary=summary(drafts);GapAnalysisEntity analysis=new GapAnalysisEntity();analysis.setUserId(userId);analysis.setResumeVersionId(resume.getId());analysis.setCandidateProfileSnapshotId(profile.getId());analysis.setJobRequirementVersionId(job.getId());analysis.setStatus(overall(summary));analysis.setSummaryJson(json(summary));analysis=analyses.save(analysis);for(ItemDraft draft:drafts)items.save(entity(analysis.getId(),draft));agentRuns.completeStep(policyStep,"matched="+summary.matchedRequirements()+", gap="+summary.gapRequirements()+", unknown="+summary.unknownRequirements());agentRuns.finishRun(runId,"status="+analysis.getStatus()+", weightedMatchRate="+summary.weightedMatchRate());return toResult(analysis,draftsToEntities(analysis.getId()),candidateEvidence);}catch(RuntimeException ex){agentRuns.failStep(deterministicStep,ex);agentRuns.failRun(runId,ex);throw ex;}
 }
 @Transactional(readOnly=true) public GapAnalysisDtos.Result latest(String userId,Long jobVersionId,Long resumeVersionId){resumes.findByIdAndUserId(resumeVersionId,userId).orElseThrow(()->ApiException.notFound("Resume version not found."));GapAnalysisEntity analysis=analyses.findTopByUserIdAndJobRequirementVersionIdAndResumeVersionIdOrderByCreatedAtDesc(userId,jobVersionId,resumeVersionId).orElseThrow(()->ApiException.notFound("Gap analysis not found."));CandidateProfileSnapshotEntity profile=profiles.findByResumeVersionIdAndUserId(analysis.getResumeVersionId(),userId).orElseThrow(()->ApiException.notFound("Candidate profile not found."));return toResult(analysis,items.findByGapAnalysisIdOrderByRequirementIdAsc(analysis.getId()),evidence.findByUserIdAndProfileSnapshotIdOrderByCreatedAtAsc(userId,profile.getId()));}
 private GapSemanticAssessment semantic(Long runId,String userId,StructuredJobRequirementEntity requirement,List<CandidateEvidenceEntity> matching,String resumeHash,String jobHash){Long step=agentRuns.startStep(runId,AgentStepName.GAP_SEMANTIC_ASSESSMENT,"Assess matching-skill evidence without tracing raw content.");try{Map<String,Object> requirementPayload=Map.of("skillCode",requirement.getSkillCode(),"importance",requirement.getImportance(),"requiredLevel",requirement.getRequiredLevel(),"requirementText",requirement.getRequirementText());List<Map<String,Object>> evidencePayload=matching.stream().map(e->Map.<String,Object>of("evidenceId",e.getId(),"skillCode",e.getSkillCode(),"text",e.getEvidenceText())).toList();AgentResult result=runtime.run(new GapSemanticAssessmentAgent(),new AgentContext(runId,step,userId,"candidate-job-gap-semantic-agent","Assess evidence support",AgentState.PREPARING,Map.of("requirement",requirementPayload,"candidateEvidence",evidencePayload,"requirementId",requirement.getId(),"evidenceCount",matching.size(),"sourceVersionHash",resumeHash,"jobVersionHash",jobHash),List.of(),Instant.now()));if(result.nextState()!=AgentState.COMPLETED)throw new IllegalStateException(result.completionReason());GapSemanticAssessment assessment=mapper.readValue(String.valueOf(result.output().get("semanticAssessmentJson")),GapSemanticAssessment.class);agentRuns.completeStep(step,"requirementId="+requirement.getId()+", evidenceCount="+matching.size());return normalize(assessment);}catch(Exception ex){agentRuns.failStep(step,ex);return new GapSemanticAssessment(false,EvidenceStrength.NONE,BigDecimal.ZERO,"Semantic assessment unavailable; evidence remains unknown.");}}
 private String evidenceLevel(List<CandidateEvidenceEntity> evidence){return "";} // Phase 2A evidence has no reliable level; policy routes matching skills to semantic review.
 private GapSemanticAssessment normalize(GapSemanticAssessment value){if(value==null)return new GapSemanticAssessment(false,EvidenceStrength.NONE,BigDecimal.ZERO,"Semantic assessment returned no result.");BigDecimal confidence=value.confidence()==null?BigDecimal.ZERO:value.confidence().max(BigDecimal.ZERO).min(BigDecimal.ONE);return new GapSemanticAssessment(value.supported(),value.evidenceStrength()==null?EvidenceStrength.NONE:value.evidenceStrength(),confidence,compact(value.reason(),1200));}
 private GapAnalysisItemEntity entity(Long analysisId,ItemDraft draft){GapAnalysisItemEntity e=new GapAnalysisItemEntity();e.setGapAnalysisId(analysisId);e.setRequirementId(draft.requirement().getId());e.setSkillCode(draft.requirement().getSkillCode());e.setRequirementText(draft.requirement().getRequirementText());e.setImportance(draft.requirement().getImportance());e.setRequiredLevel(draft.requirement().getRequiredLevel());e.setStatus(draft.decision().status());e.setCandidateEvidenceIdsJson(json(draft.evidence().stream().map(CandidateEvidenceEntity::getId).toList()));e.setEvidenceStrength(draft.decision().evidenceStrength());e.setConfidence(draft.decision().confidence());e.setReason(compact(draft.decision().reason(),1200));e.setSourceChunkId(draft.requirement().getSourceChunkId());return e;}
 private List<GapAnalysisItemEntity> draftsToEntities(Long analysisId){return items.findByGapAnalysisIdOrderByRequirementIdAsc(analysisId);}
 private GapAnalysisDtos.Summary summary(List<ItemDraft> drafts){return GapAnalysisSummaryCalculator.calculate(drafts.stream().map(d->new GapAnalysisSummaryCalculator.Input(d.requirement().getImportance(),d.decision().status())).toList());}
 private GapStatus overall(GapAnalysisDtos.Summary s){if(s.gapRequirements()>0)return GapStatus.GAP;if(s.unknownRequirements()>0)return GapStatus.UNKNOWN;return GapStatus.MATCH;}
 private GapAnalysisDtos.Result toResult(GapAnalysisEntity analysis,List<GapAnalysisItemEntity> rows,List<CandidateEvidenceEntity> evidence){GapAnalysisDtos.Summary summary=readSummary(analysis.getSummaryJson());Map<Long,CandidateEvidenceEntity> evidenceById=new HashMap<>();for(CandidateEvidenceEntity e:evidence)evidenceById.put(e.getId(),e);List<GapAnalysisDtos.Item> itemDtos=rows.stream().map(row->new GapAnalysisDtos.Item(row.getId(),row.getRequirementId(),row.getSkillCode(),row.getRequirementText(),row.getImportance(),row.getRequiredLevel(),row.getStatus(),evidenceRefs(readIds(row.getCandidateEvidenceIdsJson()),evidenceById),row.getEvidenceStrength(),row.getConfidence(),row.getReason(),row.getSourceChunkId())).toList();return new GapAnalysisDtos.Result(analysis.getId(),analysis.getResumeVersionId(),analysis.getCandidateProfileSnapshotId(),analysis.getJobRequirementVersionId(),analysis.getStatus(),summary,itemDtos,analysis.getCreatedAt());}
 private List<GapAnalysisDtos.EvidenceReference> evidenceRefs(List<Long> ids,Map<Long,CandidateEvidenceEntity> byId){return ids.stream().map(byId::get).filter(Objects::nonNull).map(e->new GapAnalysisDtos.EvidenceReference(e.getId(),e.getResumeVersionId(),e.getSkillCode(),e.getClaim(),e.getSourceReference(),e.getConfidence())).toList();}
 private GapAnalysisDtos.Summary readSummary(String value){try{return mapper.readValue(value,GapAnalysisDtos.Summary.class);}catch(Exception ex){throw new IllegalStateException("Invalid persisted gap summary.",ex);}} private List<Long> readIds(String value){try{return mapper.readValue(value,new TypeReference<List<Long>>(){});}catch(Exception ex){return List.of();}} private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception ex){throw new IllegalStateException("Cannot serialize gap analysis.",ex);}} private String compact(String value,int max){String text=value==null?"":value.trim();return text.length()<=max?text:text.substring(0,max);} private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException ex){throw new IllegalStateException(ex);}}
 private record ItemDraft(StructuredJobRequirementEntity requirement,List<CandidateEvidenceEntity> evidence,GapAnalysisPolicy.Decision decision){}
}
