package com.donotmiss.backend.aiapplication.career.gap;
import com.donotmiss.backend.aiapplication.agent.*; import com.donotmiss.backend.aiapplication.llm.*; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.stereotype.Component; import java.math.BigDecimal; import java.util.*;
/** LLM semantic judge. It receives only already-selected matching-skill evidence and cannot make final business status. */
@Component public class GapSemanticAssessmentTool implements AgentTool {
 public static final String NAME="assess_candidate_job_evidence"; private final LlmGateway gateway; private final ObjectMapper mapper; public GapSemanticAssessmentTool(LlmGateway gateway,ObjectMapper mapper){this.gateway=gateway;this.mapper=mapper;}
 public String name(){return NAME;} public String description(){return "Semantically assess selected candidate evidence against one requirement.";} public Map<String,Object> inputSchema(){return Map.of("type","object");}
 public AgentToolExecutionResult execute(AgentToolExecutionRequest request){Object requirement=request.input().get("requirement");Object evidence=request.input().get("candidateEvidence");if(requirement==null||evidence==null)throw new IllegalArgumentException("requirement and candidateEvidence are required");String prompt="Return JSON only: {supported:boolean,evidenceStrength:NONE|WEAK|MODERATE|STRONG,confidence:0..1,reason:string}. Judge only supplied evidence. Do not infer missing experience, do not give scores or recommendations.";Map<String,Object> metadata=new LinkedHashMap<>();metadata.put("runId",request.runId());metadata.put("agentName","candidate-job-gap-semantic-agent");metadata.put("requirementId",request.input().get("requirementId"));metadata.put("evidenceCount",request.input().get("evidenceCount"));Optional<LlmResponse> response=gateway.complete(new LlmRequest(null,List.of(new LlmMessage(LlmMessage.Role.SYSTEM,prompt),new LlmMessage(LlmMessage.Role.USER,toJson(Map.of("requirement",requirement,"candidateEvidence",evidence)))),0.0,1000,30000L,UUID.randomUUID().toString(),"gap-semantic-assessment-v1",LlmRequest.ResponseFormat.JSON_OBJECT,metadata));String json=response.map(LlmResponse::content).orElseGet(()->toJson(new GapSemanticAssessment(false,EvidenceStrength.NONE,BigDecimal.ZERO,"Semantic provider unavailable; no support inferred.")));return new AgentToolExecutionResult(Map.of("semanticAssessmentJson",json),response.isPresent()?"Semantic assessment completed.":"Semantic assessment unavailable; conservative unknown signal returned.");}
 private String toJson(Object value){try{return mapper.writeValueAsString(value);}catch(Exception ex){throw new IllegalStateException("Cannot serialize semantic assessment payload.",ex);}}
}
