package com.donotmiss.backend.aiapplication.career.recommendation;
import com.donotmiss.backend.aiapplication.career.gap.*; import org.junit.jupiter.api.Test; import java.math.BigDecimal; import java.time.Instant; import java.util.*; import static org.assertj.core.api.Assertions.assertThat;
class RecommendationPolicyTest {
 private final RecommendationPolicy policy=new RecommendationPolicy();
 @Test void scoresHighMatchAboveCriticalGapAndDoesNotTreatUnknownAsGap(){var high=policy.score(result(new BigDecimal(".90"),3,0,0,0));var criticalGap=policy.score(result(new BigDecimal(".90"),3,1,0,1));var unknown=policy.score(result(new BigDecimal(".90"),3,0,1,0));assertThat(high.recommendationScore()).isGreaterThan(criticalGap.recommendationScore());assertThat(unknown.recommendationScore()).isGreaterThan(criticalGap.recommendationScore());assertThat(unknown.recommendationScore()).isLessThan(high.recommendationScore());assertThat(unknown.gapCount()).isZero();assertThat(unknown.unknownCount()).isEqualTo(1);}
 @Test void explanationCountsAndTopItemsComeFromGapFacts(){var decision=policy.score(result(new BigDecimal(".80"),1,1,1,0));assertThat(decision.matchCount()).isEqualTo(1);assertThat(decision.gapCount()).isEqualTo(1);assertThat(decision.unknownCount()).isEqualTo(1);assertThat(decision.topMatches()).extracting(GapAnalysisDtos.Item::skillCode).containsExactly("JAVA_BACKEND");assertThat(decision.topGaps()).extracting(GapAnalysisDtos.Item::skillCode).containsExactly("RAG_ENGINEERING");}
 private GapAnalysisDtos.Result result(BigDecimal rate,int matches,int gaps,int unknowns,int critical){List<GapAnalysisDtos.Item> items=new ArrayList<>();if(matches>0)items.add(item("JAVA_BACKEND",GapStatus.MATCH,5));if(gaps>0)items.add(item("RAG_ENGINEERING",GapStatus.GAP,critical>0?5:3));if(unknowns>0)items.add(item("AGENT_ENGINEERING",GapStatus.UNKNOWN,3));return new GapAnalysisDtos.Result(1L,1L,1L,1L,GapStatus.UNKNOWN,new GapAnalysisDtos.Summary(matches+gaps+unknowns,matches,gaps,unknowns,rate,critical),items,Instant.now());}
 private GapAnalysisDtos.Item item(String skill,GapStatus status,int importance){return new GapAnalysisDtos.Item(1L,1L,skill,skill+" requirement",importance,"mid",status,List.of(),EvidenceStrength.STRONG,new BigDecimal(".9"),"fixture",1L);}
}
