package com.donotmiss.backend.aiapplication.career.recommendation;

import com.donotmiss.backend.aiapplication.career.ResumeVersionEntity; import com.donotmiss.backend.aiapplication.career.ResumeVersionRepository; import com.donotmiss.backend.aiapplication.career.gap.*; import com.donotmiss.backend.aiapplication.career.job.*; import com.donotmiss.backend.common.ApiException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;

/** Phase 2D consumes GapAnalysis as its fact source; it neither parses JD nor recreates matching logic. */
@Service public class RecommendationService {
 private final ResumeVersionRepository resumes; private final JobRequirementVersionRepository jobs; private final GapAnalysisService gapAnalysis; private final RecommendationPolicy policy;
 public RecommendationService(ResumeVersionRepository resumes,JobRequirementVersionRepository jobs,GapAnalysisService gapAnalysis,RecommendationPolicy policy){this.resumes=resumes;this.jobs=jobs;this.gapAnalysis=gapAnalysis;this.policy=policy;}
 @Transactional public RecommendationDtos.Response recommend(String userId,RecommendationDtos.Request request){ResumeVersionEntity resume=resumes.findByIdAndUserId(request.resumeVersionId(),userId).orElseThrow(()->ApiException.notFound("Resume version not found."));List<Long> jobIds=request.jobRequirementVersionIds().stream().distinct().toList();List<RecommendationDtos.Item> items=new ArrayList<>();for(Long jobId:jobIds){JobRequirementVersionEntity job=jobs.findByIdAndUserId(jobId,userId).orElseThrow(()->ApiException.notFound("Job requirement version not found."));if(job.getParseStatus()!=JobRequirementParseStatus.PARSED)throw ApiException.badRequest("Every recommended job must be parsed.");GapAnalysisDtos.Result gap=gapAnalysis.latest(userId,job.getId(),resume.getId());items.add(toItem(job,policy.score(gap)));}return new RecommendationDtos.Response(resume.getId(),RecommendationRanking.top(items,request.topK()==null?3:request.topK()));}
 private RecommendationDtos.Item toItem(JobRequirementVersionEntity job,RecommendationPolicy.Decision value){return new RecommendationDtos.Item(job.getId(),job.getJobRequirementId(),job.getVersionNumber(),value.recommendationScore(),value.weightedMatchRate(),value.matchCount(),value.gapCount(),value.unknownCount(),value.criticalGapCount(),value.summary(),insights(value.topMatches()),insights(value.topGaps()),insights(value.topUnknowns()));}
 private List<RecommendationDtos.RequirementInsight> insights(List<GapAnalysisDtos.Item> items){return items.stream().map(item->new RecommendationDtos.RequirementInsight(item.requirementId(),item.skillCode(),item.requirementText(),item.importance(),item.requiredLevel(),item.status(),item.evidenceStrength(),item.confidence(),item.reason(),item.sourceChunkId(),item.candidateEvidence())).toList();}
}
