package com.donotmiss.backend.aiapplication.career.job;

import com.donotmiss.backend.agentlog.*;
import com.donotmiss.backend.aiapplication.agent.*;
import com.donotmiss.backend.aiapplication.career.SkillCodeResolver;
import com.donotmiss.backend.aiapplication.retrieval.job.*;
import com.donotmiss.backend.common.ApiException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets; import java.security.*; import java.time.Instant; import java.util.*;

/** Application boundary for the Phase 2B JD vertical slice. It owns persistence; retrieval stays in its own service. */
@Service
public class JobRequirementApplicationService {
    private static final String SCHEMA_VERSION="structured-job-requirement-v1";
    private final JobRequirementVersionRepository versions; private final JobRequirementChunkRepository chunks; private final StructuredJobRequirementRepository requirements;
    private final JobRequirementChunker chunker; private final SkillCodeResolver skillCodes; private final AgentRuntime runtime; private final AgentRunService agentRuns;
    private final JobRequirementSearchIndexService index; private final JobRequirementRetrievalService retrieval; private final ObjectMapper mapper;
    public JobRequirementApplicationService(JobRequirementVersionRepository versions,JobRequirementChunkRepository chunks,StructuredJobRequirementRepository requirements,JobRequirementChunker chunker,SkillCodeResolver skillCodes,AgentRuntime runtime,AgentRunService agentRuns,JobRequirementSearchIndexService index,JobRequirementRetrievalService retrieval,ObjectMapper mapper){this.versions=versions;this.chunks=chunks;this.requirements=requirements;this.chunker=chunker;this.skillCodes=skillCodes;this.runtime=runtime;this.agentRuns=agentRuns;this.index=index;this.retrieval=retrieval;this.mapper=mapper;}

    @Transactional public JobRequirementDtos.JobRequirementVersionResponse createVersion(String userId,JobRequirementDtos.CreateJobRequirementRequest request){String jobId=request.jobRequirementId()==null||request.jobRequirementId().isBlank()?UUID.randomUUID().toString():request.jobRequirementId().trim();int version=versions.findTopByUserIdAndJobRequirementIdOrderByVersionNumberDesc(userId,jobId).map(v->v.getVersionNumber()+1).orElse(1);JobRequirementVersionEntity entity=new JobRequirementVersionEntity();entity.setUserId(userId);entity.setJobRequirementId(jobId);entity.setVersionNumber(version);entity.setSource(request.source().trim());entity.setContentText(request.content().trim());entity.setContentHash(hash(request.content().trim()));return toVersion(versions.save(entity));}
    @Transactional public JobRequirementDtos.ParseJobRequirementResponse parse(String userId,Long versionId){JobRequirementVersionEntity version=owned(userId,versionId);if(version.getParseStatus()==JobRequirementParseStatus.PARSED){return new JobRequirementDtos.ParseJobRequirementResponse(toVersion(version),JobRequirementAsyncCommands.indexing(version).idempotencyKey(),chunks.findByJobRequirementVersionIdOrderByPositionAsc(versionId).size(),requirements.findByJobRequirementVersionIdOrderByIdAsc(versionId).size());}
        version.setParseStatus(JobRequirementParseStatus.PARSING);String versionHash=hash(String.valueOf(version.getId()));Long runId=agentRuns.startRun(userId,AgentRunType.JOB_REQUIREMENT_EXTRACTION,"job-requirement-version:"+version.getId(),"jobVersionHash="+versionHash+", schema="+SCHEMA_VERSION);Long extractionStep=agentRuns.startStep(runId,AgentStepName.JOB_REQUIREMENT_EXTRACTION,"Extract structured requirements without tracing JD content.");
        try{List<JobRequirementChunkEntity> savedChunks=persistChunks(version);AgentResult outcome=runtime.run(new JobRequirementExtractionAgent(),new AgentContext(runId,extractionStep,userId,"job-requirement-extraction-agent","Extract structured job requirements",AgentState.PREPARING,Map.of("jobText",version.getContentText(),"chunks",savedChunks.stream().map(JobRequirementChunkEntity::getContent).toList(),"jobVersionHash",versionHash),List.of(),Instant.now()));if(outcome.nextState()!=AgentState.COMPLETED)throw new IllegalStateException(outcome.completionReason());StructuredJobDescription extraction=readExtraction(outcome.output());List<StructuredJobRequirementEntity> savedRequirements=persistRequirements(version,savedChunks,extraction);agentRuns.completeStep(extractionStep,"schema="+SCHEMA_VERSION+", chunkCount="+savedChunks.size()+", requirementCount="+savedRequirements.size());Long indexStep=agentRuns.startStep(runId,AgentStepName.JOB_REQUIREMENT_INDEXING,"Index normalized JD chunks.");indexChunks(savedChunks,savedRequirements);agentRuns.completeStep(indexStep,"index="+index.indexName()+", chunkCount="+savedChunks.size());version.setParseStatus(JobRequirementParseStatus.PARSED);agentRuns.finishRun(runId,"status=PARSED, chunkCount="+savedChunks.size()+", requirementCount="+savedRequirements.size());return new JobRequirementDtos.ParseJobRequirementResponse(toVersion(version),JobRequirementAsyncCommands.indexing(version).idempotencyKey(),savedChunks.size(),savedRequirements.size());}catch(RuntimeException ex){version.setParseStatus(JobRequirementParseStatus.FAILED);agentRuns.failStep(extractionStep,ex);agentRuns.failRun(runId,ex);throw ex;}
    }
    @Transactional(readOnly=true) public List<JobRequirementDtos.JobRequirementVersionResponse> list(String userId){return versions.findByUserIdOrderByCreatedAtDesc(userId).stream().map(this::toVersion).toList();}
    @Transactional(readOnly=true) public JobRequirementDtos.JobRequirementVersionResponse get(String userId,Long id){return toVersion(owned(userId,id));}
    @Transactional(readOnly=true) public List<JobRequirementDtos.StructuredRequirementResponse> requirements(String userId,Long id){owned(userId,id);return requirements.findByJobRequirementVersionIdOrderByIdAsc(id).stream().map(this::toRequirement).toList();}
    @Transactional public JobRequirementDtos.JobSearchResponse search(String userId,Long id,JobRequirementDtos.JobSearchRequest request){
        owned(userId,id); String queryHash=hash(request.query()); String mode=index.isVectorEnabled()?"BM25_RRF_OPTIONAL_VECTOR":"BM25";
        Long runId=agentRuns.startRun(userId,AgentRunType.JOB_REQUIREMENT_RETRIEVAL,"job-requirement-version:"+id,"queryHash="+queryHash+", mode="+mode);
        Long stepId=agentRuns.startStep(runId,AgentStepName.JOB_REQUIREMENT_RETRIEVAL,"Retrieve JD chunks using query hash only.");
        try { List<JobRequirementRetrievalService.JobRetrievalResult> found=retrieval.retrieve(runId,id,request.query(),request.section(),request.skillCode(),request.limit()==null?10:request.limit()); agentRuns.completeStep(stepId,"mode="+mode+", count="+found.size()); agentRuns.finishRun(runId,"status=SUCCEEDED, count="+found.size()); return new JobRequirementDtos.JobSearchResponse(found.stream().map(x->new JobRequirementDtos.JobSearchResult(x.chunkId(),x.score(),x.rank(),x.section(),x.contentHash(),x.sourceReference())).toList(),mode); }
        catch(RuntimeException ex){agentRuns.failStep(stepId,ex);agentRuns.failRun(runId,ex);throw ex;}
    }
    private List<JobRequirementChunkEntity> persistChunks(JobRequirementVersionEntity version){List<JobRequirementChunkEntity> existing=chunks.findByJobRequirementVersionIdOrderByPositionAsc(version.getId());if(!existing.isEmpty())return existing;List<JobRequirementChunkEntity> result=new ArrayList<>();for(JobRequirementChunker.ChunkDraft draft:chunker.chunk(version.getContentText())){JobRequirementChunkEntity e=new JobRequirementChunkEntity();e.setJobRequirementVersionId(version.getId());e.setSection(draft.section());e.setContent(draft.content());e.setPosition(draft.position());e.setContentHash(draft.contentHash());result.add(chunks.save(e));}return List.copyOf(result);}
    private List<StructuredJobRequirementEntity> persistRequirements(JobRequirementVersionEntity version,List<JobRequirementChunkEntity> chunkList,StructuredJobDescription extraction){List<StructuredJobRequirementEntity> existing=requirements.findByJobRequirementVersionIdOrderByIdAsc(version.getId());if(!existing.isEmpty())return existing;Map<Integer,JobRequirementChunkEntity> byPosition=new HashMap<>();for(JobRequirementChunkEntity chunk:chunkList)byPosition.put(chunk.getPosition(),chunk);List<StructuredJobRequirementEntity> result=new ArrayList<>();for(StructuredJobDescription.Requirement item:extraction.requirements()==null?List.<StructuredJobDescription.Requirement>of():extraction.requirements()){JobRequirementChunkEntity source=byPosition.get(item.sourcePosition());if(source==null&&chunkList.size()==1)source=chunkList.getFirst();if(source==null)continue;String text=compact(item.requirementText(),4000);if(text.isBlank())continue;StructuredJobRequirementEntity e=new StructuredJobRequirementEntity();e.setJobRequirementVersionId(version.getId());e.setSourceChunkId(source.getId());e.setSkillCode(skillCodes.resolveRequirementSkill(item.skill()));e.setImportance(Math.min(5,Math.max(1,item.importance()==null?3:item.importance())));e.setRequiredLevel(blank(item.requiredLevel(),"unspecified"));e.setRequirementText(text);result.add(requirements.save(e));}return List.copyOf(result);}
    private void indexChunks(List<JobRequirementChunkEntity> chunkList,List<StructuredJobRequirementEntity> requirementList){Map<Long,List<String>> codes=new HashMap<>();for(StructuredJobRequirementEntity requirement:requirementList)codes.computeIfAbsent(requirement.getSourceChunkId(),ignored->new ArrayList<>()).add(requirement.getSkillCode());for(JobRequirementChunkEntity chunk:chunkList)index.index(chunk,codes.getOrDefault(chunk.getId(),List.of()));}
    private StructuredJobDescription readExtraction(Map<String,Object> output){try{StructuredJobDescription value=mapper.readValue(String.valueOf(output.get("structuredJobDescriptionJson")),StructuredJobDescription.class);return value==null?new StructuredJobDescription(List.of()):value;}catch(Exception ex){throw new IllegalStateException("Invalid structured job requirement JSON.",ex);}}
    private JobRequirementVersionEntity owned(String userId,Long id){return versions.findByIdAndUserId(id,userId).orElseThrow(()->ApiException.notFound("Job requirement version not found."));}
    private JobRequirementDtos.JobRequirementVersionResponse toVersion(JobRequirementVersionEntity e){return new JobRequirementDtos.JobRequirementVersionResponse(e.getId(),e.getJobRequirementId(),e.getVersionNumber(),e.getSource(),e.getContentHash(),e.getParseStatus(),e.getCreatedAt(),e.getUpdatedAt());}
    private JobRequirementDtos.StructuredRequirementResponse toRequirement(StructuredJobRequirementEntity e){return new JobRequirementDtos.StructuredRequirementResponse(e.getId(),e.getJobRequirementVersionId(),e.getSkillCode(),e.getImportance(),e.getRequiredLevel(),e.getRequirementText(),e.getSourceChunkId(),e.getCreatedAt());}
    private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException ex){throw new IllegalStateException(ex);}} private String compact(String value,int max){String text=value==null?"":value.trim();return text.length()<=max?text:text.substring(0,max);} private String blank(String value,String fallback){return value==null||value.isBlank()?fallback:value.trim();}
}
