package com.donotmiss.backend.aiapplication.career;

import com.donotmiss.backend.agentlog.*;
import com.donotmiss.backend.aiapplication.agent.*;
import com.donotmiss.backend.aiapplication.capability.SkillDictionary;
import com.donotmiss.backend.aiapplication.evidence.CandidateEvidenceSourceType;
import com.donotmiss.backend.common.ApiException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.Instant; import java.util.*;

/** Vertical-slice application service. It intentionally never touches UserMemory or Ability Score. */
@Service
public class ResumeCareerApplicationService {
 private static final String SCHEMA_VERSION="structured-resume-v1"; private static final String DICTIONARY_VERSION="v1";
 private final ResumeVersionRepository resumeRepository; private final CandidateProfileSnapshotRepository profileRepository; private final CandidateEvidenceRepository evidenceRepository; private final SkillCodeResolver skillCodes; private final AgentRuntime runtime; private final AgentRunService agentRuns; private final ObjectMapper mapper;
 public ResumeCareerApplicationService(ResumeVersionRepository resumeRepository,CandidateProfileSnapshotRepository profileRepository,CandidateEvidenceRepository evidenceRepository,SkillCodeResolver skillCodes,AgentRuntime runtime,AgentRunService agentRuns,ObjectMapper mapper){this.resumeRepository=resumeRepository;this.profileRepository=profileRepository;this.evidenceRepository=evidenceRepository;this.skillCodes=skillCodes;this.runtime=runtime;this.agentRuns=agentRuns;this.mapper=mapper;}

 @Transactional public ResumeDtos.ResumeVersionResponse createVersion(String userId,ResumeDtos.CreateResumeVersionRequest request){String resumeId=request.resumeId()==null||request.resumeId().isBlank()?UUID.randomUUID().toString():request.resumeId().trim();int version=resumeRepository.findTopByUserIdAndResumeIdOrderByVersionNumberDesc(userId,resumeId).map(v->v.getVersionNumber()+1).orElse(1);ResumeVersionEntity entity=new ResumeVersionEntity();entity.setResumeId(resumeId);entity.setUserId(userId);entity.setVersionNumber(version);entity.setContentText(request.content().trim());entity.setFileReference(blankToNull(request.fileReference()));entity.setContentHash(hash(request.content().trim()));return toVersion(resumeRepository.save(entity));}
 @Transactional public ResumeDtos.CandidateProfileResponse parse(String userId,Long resumeVersionId){ResumeVersionEntity resume=ownedResume(userId,resumeVersionId);if(profileRepository.findByResumeVersionIdAndUserId(resumeVersionId,userId).isPresent())return toProfile(profileRepository.findByResumeVersionIdAndUserId(resumeVersionId,userId).orElseThrow());resume.setParseStatus(ResumeParseStatus.PARSING);String versionHash=hash(String.valueOf(resume.getId()));Long runId=agentRuns.startRun(userId,AgentRunType.RESUME_EXTRACTION,"resume-version:"+resume.getId(),"resumeVersionHash="+versionHash+", schema="+SCHEMA_VERSION);Long stepId=agentRuns.startStep(runId,AgentStepName.RESUME_EXTRACTION,"Extract structured resume without tracing content.");try{AgentResult outcome=runtime.run(new ResumeExtractionAgent(),new AgentContext(runId,stepId,userId,"resume-extraction-agent","Extract structured candidate profile",AgentState.PREPARING,Map.of("resumeText",resume.getContentText(),"sourceVersionHash",versionHash),List.of(),Instant.now()));if(outcome.nextState()!=AgentState.COMPLETED)throw new IllegalStateException(outcome.completionReason());StructuredResume structured=readStructuredResume(outcome.output());agentRuns.completeStep(stepId,"schema="+SCHEMA_VERSION+", projects="+structured.projects().size()+", skills="+structured.skills().size());CandidateProfileSnapshotEntity profile=new CandidateProfileSnapshotEntity();profile.setUserId(userId);profile.setResumeVersionId(resume.getId());profile.setProfileVersion(1);profile.setSchemaVersion(SCHEMA_VERSION);profile.setProfileJson(toJson(structured));profile.setGeneratedAt(Instant.now());profile=profileRepository.save(profile);persistEvidence(userId,resume,profile,structured);resume.setParseStatus(ResumeParseStatus.PARSED);agentRuns.finishRun(runId,"status=PARSED, evidenceCount="+evidenceRepository.findByUserIdAndProfileSnapshotIdOrderByCreatedAtAsc(userId,profile.getId()).size());return toProfile(profile);}catch(RuntimeException ex){resume.setParseStatus(ResumeParseStatus.FAILED);agentRuns.failStep(stepId,ex);agentRuns.failRun(runId,ex);throw ex;}}
 @Transactional(readOnly=true) public List<ResumeDtos.ResumeVersionResponse> versions(String userId){return resumeRepository.findByUserIdOrderByCreatedAtDesc(userId).stream().map(this::toVersion).toList();}
 @Transactional(readOnly=true) public ResumeDtos.ResumeVersionResponse getVersion(String userId,Long id){return toVersion(ownedResume(userId,id));}
 @Transactional(readOnly=true) public ResumeDtos.CandidateProfileResponse profile(String userId,Long resumeVersionId){return toProfile(profileRepository.findByResumeVersionIdAndUserId(resumeVersionId,userId).orElseThrow(()->ApiException.notFound("Candidate profile not found.")));}
 @Transactional(readOnly=true) public List<ResumeDtos.CandidateEvidenceResponse> evidence(String userId,Long resumeVersionId){CandidateProfileSnapshotEntity profile=profileRepository.findByResumeVersionIdAndUserId(resumeVersionId,userId).orElseThrow(()->ApiException.notFound("Candidate profile not found."));return evidenceRepository.findByUserIdAndProfileSnapshotIdOrderByCreatedAtAsc(userId,profile.getId()).stream().map(this::toEvidence).toList();}

 private void persistEvidence(String userId,ResumeVersionEntity resume,CandidateProfileSnapshotEntity profile,StructuredResume structured){for(StructuredResume.Project item:structured.projects())saveEvidence(userId,resume,profile,"project:"+safeId(item.id(),item.name()),"projects",item.name(),item.summary(),item.skills());for(StructuredResume.WorkExperience item:structured.workExperience())saveEvidence(userId,resume,profile,"work:"+safeId(item.id(),item.organization()),"workExperience",item.role(),item.summary(),item.skills());for(StructuredResume.Achievement item:structured.achievements())saveEvidence(userId,resume,profile,"achievement:"+safeId(item.id(),item.title()),"achievements",item.title(),item.detail(),item.skills());}
 private void saveEvidence(String userId,ResumeVersionEntity resume,CandidateProfileSnapshotEntity profile,String sourceId,String reference,String claim,String text,List<String> skills){if(text==null||text.isBlank())return;List<String> values=skills==null||skills.isEmpty()?List.of("UNMAPPED"):skills;for(String raw:values){String code=skillCodes.resolveOrUnmapped(raw);CandidateEvidenceEntity e=new CandidateEvidenceEntity();e.setUserId(userId);e.setProfileSnapshotId(profile.getId());e.setResumeVersionId(resume.getId());e.setSourceType(CandidateEvidenceSourceType.RESUME);e.setSourceId(sourceId);e.setSourceReference(reference);e.setSkillCode(code);e.setClaim(compact(claim,600));e.setEvidenceText(compact(text,4000));e.setConfidence(new BigDecimal("0.6000"));evidenceRepository.save(e);}}
 private StructuredResume readStructuredResume(Map<String,Object> output){Object json=output.get("structuredResumeJson");try{StructuredResume r=mapper.readValue(String.valueOf(json),StructuredResume.class);return normalize(r);}catch(Exception ex){throw new IllegalStateException("Invalid structured resume JSON.",ex);}}
 private StructuredResume normalize(StructuredResume r){if(r==null)throw new IllegalStateException("Empty structured resume.");return new StructuredResume(list(r.education()),list(r.projects()),list(r.workExperience()),list(r.skills()),list(r.achievements()));} private <T> List<T> list(List<T> v){return v==null?List.of():List.copyOf(v);}
 private ResumeVersionEntity ownedResume(String userId,Long id){return resumeRepository.findByIdAndUserId(id,userId).orElseThrow(()->ApiException.notFound("Resume version not found."));}
 private ResumeDtos.ResumeVersionResponse toVersion(ResumeVersionEntity e){return new ResumeDtos.ResumeVersionResponse(e.getId(),e.getResumeId(),e.getVersionNumber(),e.getContentHash(),e.getParseStatus(),e.getCreatedAt(),e.getUpdatedAt());}
 private ResumeDtos.CandidateProfileResponse toProfile(CandidateProfileSnapshotEntity e){try{return new ResumeDtos.CandidateProfileResponse(e.getId(),e.getResumeVersionId(),e.getProfileVersion(),e.getSchemaVersion(),mapper.readValue(e.getProfileJson(),StructuredResume.class),e.getGeneratedAt());}catch(JsonProcessingException ex){throw new IllegalStateException("Invalid persisted candidate profile.",ex);}}
 private ResumeDtos.CandidateEvidenceResponse toEvidence(CandidateEvidenceEntity e){return new ResumeDtos.CandidateEvidenceResponse(e.getId(),e.getResumeVersionId(),e.getProfileSnapshotId(),e.getSourceType().name(),e.getSourceId(),e.getSourceReference(),e.getSkillCode(),e.getClaim(),e.getEvidenceText(),e.getConfidence(),e.getCreatedAt());}
 private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException ex){throw new IllegalStateException(ex);}} private String toJson(Object v){try{return mapper.writeValueAsString(v);}catch(JsonProcessingException ex){throw new IllegalStateException(ex);}} private String compact(String v,int n){String x=v==null?"":v.trim();return x.length()>n?x.substring(0,n):x;} private String safeId(String id,String fallback){return id==null||id.isBlank()?hash(String.valueOf(fallback)).substring(0,16):compact(id,100);} private String blankToNull(String v){return v==null||v.isBlank()?null:v.trim();}
}
