package com.donotmiss.backend.aiapplication.career;
import com.donotmiss.backend.aiapplication.agent.*; import com.donotmiss.backend.aiapplication.llm.*; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.stereotype.Component; import java.util.*;
@Component public class ResumeExtractionTool implements AgentTool{
 public static final String NAME="extract_structured_resume"; private final LlmGateway gateway; private final ObjectMapper mapper; public ResumeExtractionTool(LlmGateway gateway,ObjectMapper mapper){this.gateway=gateway;this.mapper=mapper;}
 public String name(){return NAME;} public String description(){return "Extracts a strict structured resume from a transient text payload.";} public Map<String,Object> inputSchema(){return Map.of("type","object");}
 public AgentToolExecutionResult execute(AgentToolExecutionRequest request){Object value=request.input().get("resumeText"); if(!(value instanceof String text)||text.isBlank())throw new IllegalArgumentException("resumeText is required"); String prompt="Extract a resume into strict JSON only. Schema: {education:[{school,degree,field,period}],projects:[{id,name,summary,skills,highlights}],workExperience:[{id,organization,role,summary,skills}],skills:[{name,level}],achievements:[{id,title,detail,skills}]}. Use empty arrays for missing data. Do not invent facts.";Map<String,Object> metadata=new LinkedHashMap<>();metadata.put("runId",request.runId());metadata.put("agentName","resume-extraction-agent");metadata.put("sourceVersionHash",request.input().get("sourceVersionHash"));Optional<LlmResponse> response=gateway.complete(new LlmRequest(null,List.of(new LlmMessage(LlmMessage.Role.SYSTEM,prompt),new LlmMessage(LlmMessage.Role.USER,text)),0.1,1800,60000L,UUID.randomUUID().toString(),"resume-extraction-v1",LlmRequest.ResponseFormat.JSON_OBJECT,metadata));String json=response.map(LlmResponse::content).orElseGet(()->toJson(fallback(text)));return new AgentToolExecutionResult(Map.of("structuredResumeJson",json),response.isPresent()?"Structured resume extracted by LLM.":"Structured resume extracted by rule fallback.");}
 private StructuredResume fallback(String text){List<String> skills=new ArrayList<>();for(String term:List.of("Java","Spring Boot","RAG","Agent","LLM","Python")){if(text.toLowerCase(Locale.ROOT).contains(term.toLowerCase(Locale.ROOT)))skills.add(term);}List<StructuredResume.Skill> skillItems=skills.stream().map(v->new StructuredResume.Skill(v,"unspecified")).toList();List<StructuredResume.Project> projects=text.isBlank()?List.of():List.of(new StructuredResume.Project("project-1","Resume project experience",compact(text,1200),skills,List.of()));return new StructuredResume(List.of(),projects,List.of(),skillItems,List.of());}
 private String toJson(StructuredResume value){try{return mapper.writeValueAsString(value);}catch(Exception ex){throw new IllegalStateException("Cannot serialize fallback resume.",ex);}} private String compact(String v,int max){return v.length()<=max?v:v.substring(0,max);}
}
