<script setup lang="ts">
import { LoaderCircle, Search, Sparkles } from "@lucide/vue";
import { onMounted, ref } from "vue";
import { careerApi, jobRequirementApi, recommendationApi } from "@/api/career";
import type { GapAnalysisResult, JobRecommendation, JobRequirementVersion, JobSearchResult, ResumeVersion, StructuredJobRequirement } from "@/types/career";

const content = ref("");
const versions = ref<JobRequirementVersion[]>([]);
const selected = ref<JobRequirementVersion | null>(null);
const requirements = ref<StructuredJobRequirement[]>([]);
const query = ref("");
const results = ref<JobSearchResult[]>([]);
const mode = ref("");
const resumeVersions = ref<ResumeVersion[]>([]);
const resumeVersionId = ref<number | null>(null);
const gap = ref<GapAnalysisResult | null>(null);
const selectedRecommendationJobs = ref<number[]>([]);
const recommendations = ref<JobRecommendation[]>([]);
const busy = ref(false);
const message = ref("");

onMounted(load);
async function load() { try { [versions.value, resumeVersions.value] = await Promise.all([jobRequirementApi.versions(), careerApi.versions()]); selected.value = versions.value[0] ?? null; resumeVersionId.value = resumeVersions.value.find((version) => version.parseStatus === "PARSED")?.id ?? null; if (selected.value?.parseStatus === "PARSED") { await loadRequirements(); await loadGap(); } } catch { message.value = "JD 版本加载失败"; } }
async function createAndParse() { if (!content.value.trim() || busy.value) return; busy.value = true; message.value = ""; try { const version = await jobRequirementApi.create(content.value); selected.value = version; versions.value = [version, ...versions.value]; const parsed = await jobRequirementApi.parse(version.id); selected.value = parsed.version; await loadRequirements(); message.value = `已解析 ${parsed.requirementCount} 条要求、${parsed.chunkCount} 个分块`; } catch (error) { message.value = error instanceof Error ? error.message : "JD 解析失败"; } finally { busy.value = false; } }
async function choose(version: JobRequirementVersion) { selected.value = version; requirements.value = []; results.value = []; gap.value = null; if (version.parseStatus === "PARSED") { await loadRequirements(); await loadGap(); } }
async function loadRequirements() { if (!selected.value) return; try { requirements.value = await jobRequirementApi.requirements(selected.value.id); } catch { message.value = "Structured Requirements 读取失败"; } }
async function search() { if (!selected.value || !query.value.trim()) return; try { const response = await jobRequirementApi.search(selected.value.id, query.value); results.value = response.results; mode.value = response.mode; } catch { message.value = "检索失败；请确认 JD 已解析且搜索基础设施已启用。"; } }
async function analyzeGap() { if (!selected.value || !resumeVersionId.value) return; busy.value = true; try { gap.value = await jobRequirementApi.analyzeGap(selected.value.id, resumeVersionId.value); } catch { message.value = "Gap Analysis 失败；请确认该简历已完成解析。"; } finally { busy.value = false; } }
async function loadGap() { if (!selected.value || !resumeVersionId.value) return; try { gap.value = await jobRequirementApi.gapAnalysis(selected.value.id, resumeVersionId.value); } catch { gap.value = null; } }
function toggleRecommendationJob(jobId: number) { selectedRecommendationJobs.value = selectedRecommendationJobs.value.includes(jobId) ? selectedRecommendationJobs.value.filter((id) => id !== jobId) : [...selectedRecommendationJobs.value, jobId]; }
async function recommend() { if (!resumeVersionId.value || !selectedRecommendationJobs.value.length) return; busy.value = true; message.value = ""; try { const response = await recommendationApi.recommend(resumeVersionId.value, selectedRecommendationJobs.value, 3); recommendations.value = response.recommendations; } catch { message.value = "岗位推荐失败；请确认所选 JD 和简历均已完成解析。"; } finally { busy.value = false; } }
function marker(status: string) { return status === "MATCH" ? "✓" : status === "GAP" ? "✗" : "△"; }
function rankLabel(index: number) { return ["①", "②", "③"][index] ?? `${index + 1}.`; }
function shortId(value: string) { return value.slice(0, 8); }
function shortHash(value: string) { return value.slice(0, 12); }
function formatCreatedAt(value: string) { return new Date(value).toLocaleString(); }
</script>

<template>
  <section class="career-workspace">
    <header class="module-page-heading"><div><p class="eyebrow">Job Requirement RAG</p><h2>JD 解析与混合检索</h2><p>纯文本 JD 会生成不可变版本、结构化要求和可引用的 section-aware chunk。</p></div></header>
    <section class="career-grid">
      <article class="career-input"><h3><Sparkles :size="18" /> 输入 JD 文本</h3><textarea v-model="content" rows="14" maxlength="50000" placeholder="粘贴纯文本 JD，例如：岗位职责、任职要求、技术栈、加分项。"></textarea><button type="button" :disabled="busy || !content.trim()" @click="createAndParse"><LoaderCircle v-if="busy" class="spin" :size="17" /><Sparkles v-else :size="17" />{{ busy ? "解析中" : "创建版本并解析" }}</button><p v-if="message" class="module-error">{{ message }}</p></article>
      <article class="career-versions"><h3>JD 版本</h3><button v-for="version in versions" :key="version.id" type="button" :class="{ 'is-active': selected?.id === version.id }" @click="choose(version)"><strong>JD · v{{ version.version }}</strong><span>{{ version.parseStatus }} · ID {{ shortId(version.jobRequirementId) }}</span><small>Hash {{ shortHash(version.contentHash) }}… · {{ formatCreatedAt(version.createdAt) }}</small></button><p v-if="!versions.length">还没有 JD 版本。</p></article>
    </section>
    <section v-if="selected?.parseStatus === 'PARSED'" class="career-output"><header><div><p class="eyebrow">Structured Requirements</p><h3>稳定 Skill Code</h3></div><small>{{ requirements.length }} 条</small></header><div v-if="!requirements.length" class="module-empty">未抽取到可结构化的要求。</div><article v-for="item in requirements" :key="item.id" class="career-evidence"><div><strong>{{ item.skillCode }}</strong><span>重要度 {{ item.importance }}/5 · {{ item.requiredLevel }} · chunk {{ item.sourceChunkId }}</span></div><p>{{ item.requirementText }}</p></article></section>
    <section v-if="selected?.parseStatus === 'PARSED'" class="career-output"><header><div><p class="eyebrow">Retrieval Test</p><h3>检索 JD 证据</h3></div><small>{{ mode }}</small></header><div class="career-search"><input v-model="query" placeholder="例如：Java Spring Boot REST API" @keyup.enter="search" /><button type="button" @click="search"><Search :size="16" />检索</button></div><article v-for="result in results" :key="result.chunkId" class="career-evidence"><div><strong>#{{ result.rank }} · {{ result.section }}</strong><span>score {{ result.score.toFixed(4) }} · chunk {{ result.chunkId }}</span></div><small>{{ result.sourceReference }} · {{ result.contentHash.slice(0, 12) }}…</small></article></section>
    <section v-if="selected?.parseStatus === 'PARSED'" class="career-output"><header><div><p class="eyebrow">Candidate–Job Gap Analysis</p><h3>Job Match Overview</h3></div><button type="button" :disabled="busy || !resumeVersionId" @click="analyzeGap">{{ busy ? "分析中" : "运行 Gap Analysis" }}</button></header><label class="career-select">候选人简历版本<select v-model.number="resumeVersionId" @change="loadGap"><option :value="null">选择已解析简历</option><option v-for="version in resumeVersions.filter((item) => item.parseStatus === 'PARSED')" :key="version.id" :value="version.id">Resume v{{ version.version }}</option></select></label><div v-if="gap" class="gap-summary"><span><strong>{{ gap.summary.matchedRequirements }}</strong>Matched</span><span><strong>{{ gap.summary.gapRequirements }}</strong>Gaps</span><span><strong>{{ gap.summary.unknownRequirements }}</strong>Unknown</span><span><strong>{{ Math.round(gap.summary.weightedMatchRate * 100) }}%</strong>Weighted Match</span></div><div v-if="gap" class="gap-items"><article v-for="item in gap.items" :key="item.id" class="career-evidence" :class="`gap-${item.status.toLowerCase()}`"><div><strong>{{ marker(item.status) }} {{ item.skillCode }}</strong><span>重要度 {{ item.importance }}/5 · {{ item.requiredLevel }} · JD chunk {{ item.sourceChunkId }}</span></div><p>{{ item.requirementText }}</p><small>{{ item.status }} · {{ item.evidenceStrength }} · confidence {{ item.confidence.toFixed(2) }}</small><p v-for="evidence in item.candidateEvidence" :key="evidence.evidenceId">Evidence: {{ evidence.claim }} <small>· Resume {{ evidence.resumeVersionId }} · {{ evidence.sourceReference }}</small></p><small>{{ item.reason }}</small></article></div><p v-else class="module-empty">选择一个已解析的简历版本后运行分析。无证据会保持 UNKNOWN，不会推测候选人具备能力。</p></section>
    <section class="career-output"><header><div><p class="eyebrow">Recommendation</p><h3>推荐岗位 TOP 3</h3></div><button type="button" :disabled="busy || !resumeVersionId || !selectedRecommendationJobs.length" @click="recommend">{{ busy ? "推荐中" : "开始推荐" }}</button></header><p class="module-empty">选择多个已解析 JD。排序只使用该简历版本对应的 Gap Analysis 结果。</p><div class="recommendation-picker"><label v-for="job in versions.filter((item) => item.parseStatus === 'PARSED')" :key="job.id"><input type="checkbox" :checked="selectedRecommendationJobs.includes(job.id)" @change="toggleRecommendationJob(job.id)" /><span>JD · v{{ job.version }} · {{ job.parseStatus }} · ID {{ shortId(job.jobRequirementId) }} · Hash {{ shortHash(job.contentHash) }}</span></label></div><article v-for="(recommendation, index) in recommendations" :key="recommendation.jobRequirementVersionId" class="career-evidence recommendation-item"><div><strong>{{ rankLabel(index) }} · JD v{{ recommendation.jobVersion }}</strong><span>匹配度 {{ Math.round(recommendation.recommendationScore * 100) }}% · weighted {{ Math.round(recommendation.weightedMatchRate * 100) }}%</span></div><p>{{ recommendation.summary }}</p><small>MATCH {{ recommendation.matchCount }} · GAP {{ recommendation.gapCount }} · UNKNOWN {{ recommendation.unknownCount }} · Critical GAP {{ recommendation.criticalGapCount }}</small><p v-if="recommendation.topMatches.length">主要优势：{{ recommendation.topMatches.map((item) => item.skillCode).join(" / ") }}</p><p v-if="recommendation.topGaps.length">主要缺口：{{ recommendation.topGaps.map((item) => item.skillCode).join(" / ") }}</p><small v-if="recommendation.topUnknowns.length">待确认：{{ recommendation.topUnknowns.map((item) => item.skillCode).join(" / ") }}</small></article></section>
  </section>
</template>
